from . import tagging
from . import equipment
from . import tagging_record_reject_wizard
from . import tagging_record_close_wizard
from . import category_problem
from . import tagging_pic_work_center
from . import barcode_tagging
from . import tagging_wo_spare_part
from . import tagging_wo_spare_part_wizard
from . import tagging_bom_import_wizard