from . import res_company
from . import stock_picking
from . import stock_picking_type
from . import stock_move
from . import stock_move_line
from . import stock_quant
from . import stock_location
from . import stock_lot
from . import stock_package
from . import stock_rule
from . import product_template
from . import product_product
from . import product_packaging
from . import storage_location
from . import stock_sap
from . import uom_uom
